// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DownloadFromURL(arg1:string):Promise<models.Diagram>;

export function Greet(arg1:string):Promise<string>;

export function OpenLocalFile():Promise<models.Diagram>;
