// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function DeleteTempFile(arg1:string):Promise<void>;

export function DownloadFromURL(arg1:string):Promise<models.Diagram>;

export function ReadFile(arg1:string):Promise<string>;
