// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteTempFile(arg1) {
  return window['go']['main']['App']['DeleteTempFile'](arg1);
}

export function DownloadFromURL(arg1) {
  return window['go']['main']['App']['DownloadFromURL'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}
