// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFromURL(arg1) {
  return window['go']['main']['App']['DownloadFromURL'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenLocalFile() {
  return window['go']['main']['App']['OpenLocalFile']();
}
